name: Personal Identity Action

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2004968@ds.study.iitm.ac.in
        run: echo "Action triggered successfully for Vaishali!"
